openapi3.yml

logintとaccoutを追加したよ

---

server/go.mod
server/go.sum
server/internal/session/info.go
server/internal/session/session.go

ログインに成功したら`CreateSession`を呼ぶことでセッション情報をもつCookieを乗せられます.

セッション(のためのCookie)を生成する処理を追加

---

server/go.mod
server/go.sum
server/internal/model/auth.go
server/internal/model/model.go
server/internal/model/user.go
server/internal/routers/api/auth.go

db連携のmodelの雛形作成

---

openapi3.yml

openapiのrequest部分の修正

---

server/docker-compose.yml

`var/lib/mysql`の永続化をバインドマウントからボリュームへ変更

---

server/cmd/server/main.go
server/internal/model/model.go

データベースと接続する処理を追加

---

server/internal/model/auth.go
server/internal/routers/api/auth.go
server/internal/routers/router.go

Login処理を作成してみた
セッション・クッキー周りの確認必要

login処理の作成

---

server/internal/routers/api/auth.go
server/internal/routers/api/hello.go
server/internal/routers/router.go
server/internal/session/middleware.go
server/internal/session/session.go

ログイン状態を確認するミドルウェアを追加

---

client/src/app/user/userSlice.ts
client/src/components/LoginForm.tsx
client/src/components/LoginedHome.tsx
server/internal/room/connect.go

Fix client room

---

server/internal/model/model.go
server/internal/model/user.go
server/internal/model/ws_receive.go
server/internal/room/admin.go
server/internal/room/client.go
server/internal/room/connect.go
server/internal/room/message.go
server/internal/room/room.go
server/internal/room/room_test.go
server/internal/routers/router.go
server/internal/session/session.go

`gofmt -w .`の実行

---

server/internal/game/context.go
server/internal/game/phase.go
server/internal/room/message.go
server/internal/room/room.go

game.Context

---

server/internal/game/context.go
server/internal/model/ws_receive.go
server/internal/room/client.go
server/internal/room/message.go

フロントエンドから受け取った値をクライアントでよしなに処理して、roomに投げるようにしてる

Feature server game front client dataflow

---

server/internal/room/room.go

r.handleMessageFromAnswerer, r.handleMessageQuestionerCheckの仮実装

---

.github/workflows/server-action.yml
server/internal/game/context.go
server/internal/game/phase.go
server/internal/room/client.go
server/internal/room/connect.go
server/internal/room/message.go
server/internal/room/room.go
server/internal/room/room_test.go

room->clientsにdescriptionsを5連続で送るところまで実装

Feature server game internal

---

server/docker-compose.yml
server/internal/chatgpt/chatgpt.go

export OPENAI_API_KEY={{sk-xxxxxxxxxxx}}
してください。

環境変数からAPI_KEYを読み込むようにした

---

client/src/components/StandbyGame.tsx
server/internal/model/ws_receive.go
server/internal/model/ws_send.go
server/internal/room/client.go
server/internal/room/message.go
server/internal/room/room.go

ゲームキャンセルボタン

---

server/internal/model/ws_send.go
server/internal/room/client.go
server/internal/room/message.go
server/internal/room/room.go

一旦部屋にいる全員にコマンドを送った後に、部屋諸共消滅させるようにした

ゲーム中にクライアントの接続が終了した場合の処理

---

client/package-lock.json
client/package.json
client/src/components/GameComponents.tsx
client/src/components/Questioner.tsx

タイプライター風表示実装

---

server/internal/game/context.go
server/internal/model/ws_send.go
server/internal/room/client.go
server/internal/room/message.go
server/internal/room/room.go

websocket game_descriptionの変更

---

server/internal/room/room.go

待機画面で部屋から抜ける時にdisconnetしないように修正
